name: Build C# Project

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # 使用 .NET 7, 根据需要调整版本

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release -f net8.0

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: csharp-package
        path: ./
